
modLoader="javafml"
loaderVersion = "[47,)"
license = "All rights reserved"

[[mods]]
modId="moreartifacts"
version="1.20.1"
displayName="More Artifacts"
authors="gobies"
description='''more artifacts!'''

[[dependencies.moreartifacts]]
modId="forge"
mandatory= true
versionRange = "[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.moreartifacts]]
modId="minecraft"
mandatory= true
versionRange = "[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.moreartifacts]]
modId = "curios"
mandatory = true
versionRange = "[5.2.0+1.20.1,)"
ordering = "NONE"
side = "BOTH"